version: 2
jobs:
  test:
    docker:
      - image: rust
    steps:
      - checkout
      - run: cargo install cargo-test-junit
      - run: cargo test-junit --name ~/test_results/output.xml
      - store_test_results:
          path: ~/test_results
      - store_artifacts:
          path: ~/test_results

workflows:
  version: 2
  build:
    jobs:
      - test